apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ta-laravel-rest-api
  namespace: '994483634860'
  selfLink: /apis/serving.knative.dev/v1/namespaces/994483634860/services/ta-laravel-rest-api
  uid: 9010755a-84f0-44dd-a66b-a3fc2e39a571
  resourceVersion: AAX8J/9Tv90
  generation: 25
  creationTimestamp: '2023-05-19T16:08:00.371744Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: c616f98d-23a5-4566-b70e-3e48aadf6eee
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: bagusaditya1899@gmail.com
    serving.knative.dev/lastModifier: bagusaditya1899@gmail.com
    run.googleapis.com/operation-id: 8d94ca7e-38cf-4e41-8331-d591afde511c
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: poetic-chariot-353217:us-central1:postgreinstiki
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 994483634860-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/poetic-chariot-353217/github.com/baharma/ta-laravel-rest-api@sha256:8a970a200cb606cb91faa9eff9d10e75cbab277c75172926e7d0d49d922ccdae
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: APP_NAME
          value: TA Instiki
        - name: APP_URL
          value: https://cms.Instiki.co/
        - name: APP_ENV
          value: Staging
        - name: APP_DEBUG
          value: 'true'
        - name: LOG_CHANNEL
          value: 'null'
        - name: LOG_DEPRECATIONS_CHANNEL
          value: 'null'
        - name: LOG_LEVEL
          value: debug
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: 34.31.13.45
        - name: DB_PORT
          value: '5432'
        - name: DB_DATABASE
          value: postgres
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: NHr6tNBC$%g[g0dX
        - name: DB_SCHEMA
          value: postgres
        - name: JWT_SECRET
          value: sr8W6iQa9B9hczXas0zeTU3ZFuhhiuXF3ukFVSi06wrmMF97Usyd2cyxyOB7D0Cc
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - revisionName: ta-laravel-rest-api-00016-8wm
    percent: 100
status:
  observedGeneration: 25
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2023-05-20T23:00:01.156061Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2023-05-20T23:00:01.156061Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2023-05-20T09:11:30.934587Z'
  latestReadyRevisionName: ta-laravel-rest-api-00024-r45
  latestCreatedRevisionName: ta-laravel-rest-api-00024-r45
  traffic:
  - revisionName: ta-laravel-rest-api-00016-8wm
    percent: 100
  url: https://ta-laravel-rest-api-xjgft6ih7a-uc.a.run.app
  address:
    url: https://ta-laravel-rest-api-xjgft6ih7a-uc.a.run.app
