name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "cms-staging",
        "--image",
        "asia-southeast2-docker.pkg.dev/alterstay-production/private/cms:$TAG_NAME",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--add-cloudsql-instances",
        "alterstay-production:asia-southeast2:pgsql-alterbook",
        "--set-env-vars=APP_NAME=Instiki Api",
        "--set-env-vars=APP_ENV=staging",
        "--set-env-vars=APP_DEBUG=true",
        "--set-env-vars=LOG_CHANNEL=stack",
        "--set-env-vars=LOG_DEPRECATIONS_CHANNEL=null",
        "--set-env-vars=LOG_LEVEL=debug",
        "--set-env-vars=DB_CONNECTION=pgsql",
        "--set-env-vars=DB_DATABASE=postgres",
        "--set-env-vars=DB_SCHEMA=postgres",
        "--set-env-vars=DB_HOST=/cloudsql/poetic-chariot-353217:us-central1:postgreinstiki",
        "--set-secrets=APP_KEY=cms-staging-key:latest",
        "--set-secrets=DB_USERNAME=postgres",
        "--set-secrets=DB_PASSWORD=NHr6tNBC$%g[g0dX",
        "--port=80",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
